# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

  [build.rollupOptions.external]
    package = "pkg-notion_astro"

[[plugins]] 
  package = "netlify-plugin-cypress"
